"""empty message

Revision ID: 97dcef96ead5
Revises: 34077939c2ad
Create Date: 2020-07-17 12:59:59.381887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dcef96ead5'
down_revision = '34077939c2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
